from __future__ import annotations

import json
from pathlib import Path

from pydantic import BaseModel

from perflens.contracts.artifacts import (
    AnalysisArtifact,
    AnalysisVerificationArtifact,
    ArtifactReference,
    ArtifactTextPage,
    BenchmarkArtifact,
    BenchmarkComparison,
    BenchmarkEnvironment,
    BenchmarkMetric,
    BenchmarkMetricComparison,
    CallPath,
    CallPathDelta,
    CallPathPage,
    Classification,
    ClassificationPage,
    CollectionArtifact,
    CollectionEvidenceProvenance,
    CollectorAcceptanceArtifact,
    CollectorDeploymentArtifact,
    CollectorHealthArtifact,
    CollectorModeSwitchArtifact,
    CollectorPolicyUpdateArtifact,
    CollectorProfileSwitchArtifact,
    CollectorSetupArtifact,
    CollectorSpoolArchiveArtifact,
    CollectorSpoolArchiveEntry,
    CollectorSpoolArchiveManifest,
    CollectorSpoolArchiveVerificationArtifact,
    CollectorSpoolPruneArtifact,
    CollectorSpoolStatusArtifact,
    CollectorUndeploymentArtifact,
    CollectorUpgradeArtifact,
    ConversionProvenance,
    DiagnosisBundle,
    ElfMetadataArtifact,
    Evidence,
    EvidenceQuality,
    Frame,
    Hotspot,
    HotspotDetails,
    HotspotPage,
    PerfStatMetric,
    ProfileComparison,
    ProfileHotspotDelta,
    ProfileMetadata,
    ProjectRunArtifact,
    RuntimeStatusArtifact,
    SetupArtifact,
    SourceContextArtifact,
    SourceResolutionArtifact,
    StackSample,
    VerificationCheck,
)
from perflens.contracts.docker import (
    ContainerMatchedComparisonArtifact,
    ContainerMeasurementArtifact,
    ContainerModuleSnapshotArtifact,
    ContainerOptimizationSessionArtifact,
    ContainerProcessInventoryArtifact,
    ContainerResourceContextArtifact,
    ContainerRunArtifact,
    ContainerSymbolContextArtifact,
    ContainerTargetArtifact,
    ContainerWorkloadSpecArtifact,
    DockerRuntimeCapabilityArtifact,
)
from perflens.contracts.docker_build import (
    DockerBuildArtifact,
    DockerBuildCapabilityArtifact,
    DockerBuildContextArtifact,
    DockerBuildRecipeArtifact,
    DockerOptimizationPreviewArtifact,
    DockerOptimizationSessionArtifact,
)
from perflens.contracts.runtime_locks import (
    RuntimeAdapterCapabilityArtifact,
    RuntimeLockAnalysisArtifact,
    RuntimeLockAnalysisVerificationArtifact,
    RuntimeLockEvidenceArtifact,
    RuntimeLockImportHeader,
)
from perflens.contracts.trace import (
    LockAnalysisArtifact,
    OffCpuAnalysisArtifact,
    SchedulerAnalysisArtifact,
    TraceAnalysisVerificationArtifact,
    TraceEvidenceArtifact,
)


def test_checked_in_json_schemas_match_contract_models() -> None:
    project_root = Path(__file__).resolve().parents[2]
    schema_root = project_root / "schemas"
    models: dict[str, type[BaseModel]] = {
        "analysis.schema.json": AnalysisArtifact,
        "analysis-verification.schema.json": AnalysisVerificationArtifact,
        "verification-check.schema.json": VerificationCheck,
        "conversion-provenance.schema.json": ConversionProvenance,
        "collection-evidence-provenance.schema.json": CollectionEvidenceProvenance,
        "evidence-quality.schema.json": EvidenceQuality,
        "profile.schema.json": ProfileMetadata,
        "sample.schema.json": StackSample,
        "frame.schema.json": Frame,
        "hotspot.schema.json": Hotspot,
        "call-path.schema.json": CallPath,
        "elf-metadata.schema.json": ElfMetadataArtifact,
        "source-resolution.schema.json": SourceResolutionArtifact,
        "source-context.schema.json": SourceContextArtifact,
        "classification.schema.json": Classification,
        "diagnosis-bundle.schema.json": DiagnosisBundle,
        "evidence.schema.json": Evidence,
        "artifact-reference.schema.json": ArtifactReference,
        "artifact-text-page.schema.json": ArtifactTextPage,
        "hotspot-page.schema.json": HotspotPage,
        "hotspot-details.schema.json": HotspotDetails,
        "call-path-page.schema.json": CallPathPage,
        "classification-page.schema.json": ClassificationPage,
        "collector-deployment.schema.json": CollectorDeploymentArtifact,
        "collector-setup.schema.json": CollectorSetupArtifact,
        "collector-mode-switch.schema.json": CollectorModeSwitchArtifact,
        "collector-profile-switch.schema.json": CollectorProfileSwitchArtifact,
        "collector-acceptance.schema.json": CollectorAcceptanceArtifact,
        "collector-health.schema.json": CollectorHealthArtifact,
        "collector-policy-update.schema.json": CollectorPolicyUpdateArtifact,
        "collector-spool-status.schema.json": CollectorSpoolStatusArtifact,
        "collector-spool-archive.schema.json": CollectorSpoolArchiveArtifact,
        "collector-spool-archive-entry.schema.json": CollectorSpoolArchiveEntry,
        "collector-spool-archive-manifest.schema.json": CollectorSpoolArchiveManifest,
        "collector-spool-archive-verification.schema.json": (
            CollectorSpoolArchiveVerificationArtifact
        ),
        "collector-spool-prune.schema.json": CollectorSpoolPruneArtifact,
        "collector-undeployment.schema.json": CollectorUndeploymentArtifact,
        "collector-upgrade.schema.json": CollectorUpgradeArtifact,
        "benchmark.schema.json": BenchmarkArtifact,
        "benchmark-metric.schema.json": BenchmarkMetric,
        "benchmark-environment.schema.json": BenchmarkEnvironment,
        "benchmark-comparison.schema.json": BenchmarkComparison,
        "benchmark-metric-comparison.schema.json": BenchmarkMetricComparison,
        "profile-comparison.schema.json": ProfileComparison,
        "profile-hotspot-delta.schema.json": ProfileHotspotDelta,
        "call-path-delta.schema.json": CallPathDelta,
        "collection.schema.json": CollectionArtifact,
        "perf-stat-metric.schema.json": PerfStatMetric,
        "project-run.schema.json": ProjectRunArtifact,
        "runtime-status.schema.json": RuntimeStatusArtifact,
        "setup.schema.json": SetupArtifact,
        "trace-evidence.schema.json": TraceEvidenceArtifact,
        "scheduler-analysis.schema.json": SchedulerAnalysisArtifact,
        "off-cpu-analysis.schema.json": OffCpuAnalysisArtifact,
        "lock-analysis.schema.json": LockAnalysisArtifact,
        "trace-analysis-verification.schema.json": TraceAnalysisVerificationArtifact,
        "runtime-adapter-capability.schema.json": RuntimeAdapterCapabilityArtifact,
        "runtime-lock-evidence.schema.json": RuntimeLockEvidenceArtifact,
        "runtime-lock-analysis.schema.json": RuntimeLockAnalysisArtifact,
        "runtime-lock-analysis-verification.schema.json": (
            RuntimeLockAnalysisVerificationArtifact
        ),
        "runtime-lock-import-header.schema.json": RuntimeLockImportHeader,
        "docker-runtime-capability.schema.json": DockerRuntimeCapabilityArtifact,
        "docker-build-capability.schema.json": DockerBuildCapabilityArtifact,
        "docker-build-recipe.schema.json": DockerBuildRecipeArtifact,
        "docker-build-context.schema.json": DockerBuildContextArtifact,
        "docker-build.schema.json": DockerBuildArtifact,
        "docker-optimization-preview.schema.json": DockerOptimizationPreviewArtifact,
        "docker-optimization-session.schema.json": DockerOptimizationSessionArtifact,
        "container-target.schema.json": ContainerTargetArtifact,
        "container-process-inventory.schema.json": ContainerProcessInventoryArtifact,
        "container-resource-context.schema.json": ContainerResourceContextArtifact,
        "container-module-snapshot.schema.json": ContainerModuleSnapshotArtifact,
        "container-symbol-context.schema.json": ContainerSymbolContextArtifact,
        "container-workload-spec.schema.json": ContainerWorkloadSpecArtifact,
        "container-optimization-session.schema.json": ContainerOptimizationSessionArtifact,
        "container-run.schema.json": ContainerRunArtifact,
        "container-measurement.schema.json": ContainerMeasurementArtifact,
        "container-matched-comparison.schema.json": ContainerMatchedComparisonArtifact,
    }

    for filename, model in models.items():
        checked_in = json.loads((schema_root / filename).read_text(encoding="utf-8"))
        assert checked_in == model.model_json_schema(), filename
